version: '3.4'

services:
  
  mssql:
    image: microsoft/mssql-server-linux:2017-latest
    
    volumes:
      - mssql_server_data:/var/opt/mssql/data
    environment:
      ACCEPT_EULA: Y
      MSSQL_PID: Express
      SA_PASSWORD: MyPassword123456
    ports:
      - "1433:1433"

  vin.webapi:
    image: ${DOCKER_REGISTRY-}vin.webapi
    build:
      context: .
      dockerfile: VIN.WebApi/Dockerfile
    depends_on:
      - mssql

volumes:
  mssql_server_data:
